name: Build and Publish Go Classes Pointers

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build and Publish What Is Golang]
    types:
      - completed

jobs:
  log_context_values:
    name: Log Context Values
    runs-on: ubuntu-latest
    steps:
      - name: Log Jobs Context
        id: github_context-step
        run: echo '${{ toJSON(job) }}'
